services:
  n8n:
    build: .
    environment:
      LANGWATCH_API_KEY: "${LANGWATCH_API_KEY}"
      N8N_OTEL_SERVICE_NAME: "n8n"
    volumes:
      - n8n_data:/home/node/.n8n
    ports: ["5678:5678"]
volumes:
  n8n_data:
